version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: okko-tv-bot:latest
    container_name: okko-tv-bot
    env_file:
      - .env
    restart: unless-stopped


